USE DATABASE AIRLINE_DB;
CREATE SCHEMA DWH_AUDIT;

CREATE OR REPLACE TABLE PIPELINE_AUDIT_LOG(
    id NUMBER AUTOINCREMENT,
    proc_name STRING,
    affected_rows NUMBER,
    status STRING, -- SUCCESS / FAILED 
    error_message STRING, -- NULL if success 
    run_by STRING,
    run_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


SELECT * FROM PIPELINE_AUDIT_LOG;


